name: Build and push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  postgres-backup:
    name: Build and push
    runs-on: self-hosted
    steps:
      - uses: TooMuch4U/actions-clean@v2.1
      - uses: actions/checkout@v3
      - name: Cache models
        id: cache-models
        uses: actions/cache@v3
        with:
          path: ./models
          key: models-${{ hashFiles('install_models.sh') }}
      - name: Install models
        if: ${{ steps.cache-models.outputs.cache-hit != 'true' }}
        run: bash install_models.sh
      - run: |
          docker build -f ./docker/Dockerfile \
          -t twirapp/silero-tts-api-server:latest \
          --cache-from type=gha,scope=twir-silero-tts-api-server \
          --cache-to type=gha,mode=max,scope=twir-silero-tts-api-server .

          docker push twirapp/silero-tts-api-server:latest
